export const GET_INFO_START = 'GET_INFO_START';
export const GET_INFO_SUCCESS = 'GET_INFO_SUCCESS';
export const GET_INFO_FAIL = 'GET_INFO_FAIL';

export const GET_SEARCH_TERM = 'GET_SEARCH_TERM';

export const SUBMIT_SEARCH_START = 'SUBMIT_SEARCH_START';
export const SUBMIT_SEARCH_SUCCESS = 'SUBMIT_SEARCH_SUCCESS';
export const SUBMIT_SEARCH_FAIL = 'SUBMIT_SEARCH_FAIL';
