export const GET_SEARCH_TERM = 'GET_SEARCH_TERM';
export const GET_INPUT_LANGUAGE = 'GET_INPUT_LANGUAGE';
export const GET_OUTPUT_LANGUAGE = 'GET_OUTPUT_LANGUAGE';

export const SUBMIT_SEARCH_START = 'SUBMIT_SEARCH_START';
export const SUBMIT_SEARCH_SUCCESS = 'SUBMIT_SEARCH_SUCCESS';
export const SUBMIT_SEARCH_FAIL = 'SUBMIT_SEARCH_FAIL';

